### ISSUE TITLE
Update TaxNode.from_taxtable classmethod to include logic for support of unordered ranks

### ISSUE THREAD

**Issue by dhoogest** [fhcrc/taxtastic#142]
It appears that `TaxNode.from_taxtable` (and possibly other TaxNode methods) were overlooked when applying modifications in [this PR](https://github.com/fhcrc/taxtastic/pull/137), where support for new 'unordered' NCBI ranks was added. As a consequence,  invocations of  `TaxNode.from_taxtable` from packages such as https://github.com/fhcrc/deenurp/blob/070-python3/deenurp/subcommands/filter_outliers.py#L497 fail when parsing a taxtable that contains unordered ranks. 

Attached csv contains a taxtable which is suitable for testing. 
[taxonomy.csv](https://github.com/fhcrc/taxtastic/files/6416119/taxonomy.csv)

See also https://gitlab.labmed.uw.edu/molmicro/airflow/-/issues/22

**Comment by crosenth** [comment]
From TaxNode.from_taxtable
 
![valueerror](https://user-images.githubusercontent.com/1760683/117055960-9f41d980-acd0-11eb-83c8-a34445f051b3.png)

Traces back to this circular lineage in the taxonomy.csv:
 
![circular_lineage](https://user-images.githubusercontent.com/1760683/117056078-c26c8900-acd0-11eb-9c55-13454179615e.png)

NCBI has since corrected the lineage so, hopefully, everything should work again

https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=1338369
