### ISSUE TITLE
Is it possible to run pplacer on an IQ-tree?

### ISSUE THREAD

**Issue by AliciaArroyo** [fhcrc/taxtastic#89]
Hello, 

I was wondering if there is an implementation to run pplacer on an IQ-tree based reference tree. I tried to create the reference package with the log output files from IQ-tree but it doesn't allow me. 

I think it would be a cool idea to implement in the future :)

A.

**Comment by nylander** [comment]
Hi,
It doesn't seem to work at the moment. Someone need to add another parser for any log files IQ-tree may produce and add it to https://github.com/fhcrc/taxtastic/blob/master/taxtastic/utils.py.

It is, however, not very easy to see what is to be parsed (since there are now three different parsing functions for raxml, phyml, fasttree). If the authors of the taxit code could provide some comments or description in their code on exactly what they need to parse, it would be easier to contribute. Or, alternatively, convert the IQ-tree log format to any of the others.

/Johan

**Comment by BenKuhnhaeuser** [comment]
Any news on that? IQ-Tree is now so widely used that it would be really helpful to be able to feed its log files into taxtastic.
